### ISSUE TITLE
invalid response, can't use parameters

### ISSUE THREAD

**Issue by CartierPierre** [corvus-albus/moodle-local_wsgetroles#2]
Hi,
I'm trying to use your plugin on moodle 3.8. When I call : _https://yoursite.com/webservice/rest/server.php?wstoken=yOurT0k3n&moodlewsrestformat=json&wsfunction=local_wsgetroles_get_roles_
to get all roles, API responds _invalid_response_exception_

I have the same issue when using only _shortnames[0]=xxx_ or ids[0]=5

Sometimes it responds something like this :
`"id": 5,
        "name": null,
        "shortname": null,
        "description": null,
        "sortorder": null,
        "archetype": null`

**Comment by corvus-albus** [comment]
Hi,
please be patient. I hope I can have a look into the issue during the weekend.
Cheers corvus-albus

**Comment by CartierPierre** [comment]
Thx, a colleague told me there is conflicts between \<p\> tag in role description and XML-RPC protocol

**Comment by mleconte** [comment]
Hello
I detailed the result of get_all_roles() and applied the php method strip_tags on the 'description' column. This operation is only useful in the case of html formatting stored in the database, which is not conventional. So I think you can close that issue.

**Comment by corvus-albus** [comment]
Hello
Thank you for your recommendation mleconte. I will close this issue ...
